#!/usr/bin/python3
"""factorize given set of numbers in a file to product of two small numbers"""
import sys

def factorize(n):
    for i in range(2, n):
        if n % i:
            continue
        else:
            return i, n // i
    return n, 1

def main():
    if len(sys.argv)!= 2:
        print("Usage: factors <file>")
        return

    with open(sys.argv[1], 'r') as f:
        for line in f:
            num = int(line.strip())
            p, q = factorize(num)
            print(f"{num}={p}*{q}")

if __name__ == "__main__":
    main()