#!/usr/bin/python3
"""factorize given set of numbers in a file to product of two small numbers"""
import sys
import math

def factorize(n):
    factors = []
    for i in range(2, int(math.sqrt(n)) + 1):
        while n % i == 0:
            factors.append(i)
            n //= i
    if n > 1:
        factors.append(n)
    return factors

def main(file_path):
    with open(file_path, 'r') as file:
        numbers = file.readlines()
        for number in numbers:
            number = int(number.strip())
            factors = factorize(number)
            print(f"{number}={'*'.join(map(str, factors[:2]))}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    file_path = sys.argv[1]
    main(file_path)
