#!/usr/bin/python3
"""
Factorize numbers in a file into a product of two prime numbers
"""
import sys


def factorize():
    """
    A function to search file and factorize the given set of numbers into two prime numbers (format n = p*q)
    """
    try:
        file = sys.argv[1]
        with open(file) as f:
            for num_of_line in f:
                num_of_line = int(num_of_line)
                if num_of_line % 2 == 0:
                        print("{}={}*{}".format(num_of_line, num_of_line // 2, 2))
                        continue
                i = 3
                while i < num_of_line // 2:
                    if num_of_line % i == 0:
                        print("{}={}*{}".format(num_of_line, num_of_line // i, i))
                        break
                    i = i + 2
                if i == (num_of_line // 2) + 1:
                    print("{}={}*{}".format(num_of_line, num_of_line, 1))
    except (IndexError):
        pass


factorize()
